"""Stable domain types used by application services and adapters."""

from ewp_transcripts.domain.canonical import CanonicalResult, load_canonical_result
from ewp_transcripts.domain.enums import (
    DiagnosticStatus,
    DiscoverySkipReason,
    JobStateStatus,
    PlanDecision,
    WarningCode,
    WarningSeverity,
)
from ewp_transcripts.domain.models import (
    ApplicationWarning,
    AudioStream,
    ChannelClassification,
    ChannelMetrics,
    DiagnosticCheck,
    DiscoveredFile,
    DiscoveryResult,
    DoctorResult,
    DryRunResult,
    EpisodeCandidate,
    EpisodeInspection,
    ExistingResult,
    GroupedSource,
    InspectedSource,
    InspectionResult,
    JobOutputPlan,
    JobReservation,
    JobStateRecord,
    MediaProbeResult,
    PlannedOutputPaths,
    SkippedPath,
    SourceFingerprint,
    WorkDirectory,
)
from ewp_transcripts.domain.review import TranscriptReview, validate_review_base
from ewp_transcripts.domain.revision import (
    TranscriptRevision,
    load_transcript_revision,
    validate_revision_base,
)
from ewp_transcripts.domain.translation import TranscriptTranslation, load_transcript_translation

__all__ = [
    "ApplicationWarning",
    "AudioStream",
    "ChannelClassification",
    "ChannelMetrics",
    "CanonicalResult",
    "DiagnosticCheck",
    "DiagnosticStatus",
    "DiscoveredFile",
    "DiscoveryResult",
    "DiscoverySkipReason",
    "DoctorResult",
    "DryRunResult",
    "EpisodeCandidate",
    "EpisodeInspection",
    "ExistingResult",
    "GroupedSource",
    "InspectionResult",
    "InspectedSource",
    "JobOutputPlan",
    "JobReservation",
    "JobStateRecord",
    "JobStateStatus",
    "load_canonical_result",
    "MediaProbeResult",
    "PlannedOutputPaths",
    "PlanDecision",
    "SkippedPath",
    "SourceFingerprint",
    "TranscriptRevision",
    "TranscriptReview",
    "TranscriptTranslation",
    "load_transcript_revision",
    "load_transcript_translation",
    "validate_revision_base",
    "validate_review_base",
    "WarningCode",
    "WarningSeverity",
    "WorkDirectory",
]
