"use strict";
const expectedApi = "1.0";
let csrfToken = "";
let jobsSignature = "";
let openRouterKeyConfigured = false;
async function loadJson(path) { const response = await fetch(path, {headers: {"Accept": "application/json"}}); if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }
async function start() { const status = document.querySelector("#compatibility"); try { const [health, about, roots, session] = await Promise.all([loadJson("/api/v1/health"), loadJson("/api/v1/about"), loadJson("/api/v1/roots"), loadJson("/api/v1/session")]); if (health.api_version !== expectedApi) throw new Error("GUI_API_VERSION_MISMATCH"); csrfToken = session.csrf_token; openRouterKeyConfigured = session.openrouter_key_configured === true; updateOpenRouterKeyStatus(); status.textContent = "Status: local service ready"; document.querySelector("#application-version").textContent = `${about.application} v${about.application_version}`; document.querySelector("#api-version").textContent = `v${about.api_version}`; for (const [id, key] of [["license", "license_url"], ["source", "repository_url"], ["issues", "issues_url"]]) document.querySelector(`#${id}`).href = about[key]; const list = document.querySelector("#roots"); list.replaceChildren(...roots.roots.map(root => { const item = document.createElement("li"); item.textContent = root; return item; })); await refreshJobs(); await restoreReview(); setInterval(refreshJobs, 2000); } catch (error) { status.textContent = `Status: GUI_API_UNAVAILABLE: ${error.message}`; } }
function shortName(path) { return path ? path.split(/[\\/]/).pop() : "—"; }
function showSummary(kind, result, operation = {}) { const summary = document.querySelector("#operation-summary"); summary.replaceChildren(); let entries; const speakers = operation.speaker_count === "auto" ? "Auto-detect" : operation.speaker_count ?? "—"; const language = operation.language === "auto" ? `${result.language || "auto"} (auto)` : operation.language || result.language || "—"; if (kind === "inspect") { entries = [["Episodes", result.episodes?.length ?? 0], ["Files", result.discovery?.files?.length ?? 0], ["Skipped", result.discovery?.skipped?.length ?? 0], ["Language", language], ["Speakers", speakers]]; } else { const jobs = result.jobs || []; const identities = jobs.map(job => job.job_id).join(", "); const outputs = jobs.map(job => shortName(job.outputs?.results || job.existing_result?.path)).join(", "); entries = [["Jobs", identities ? `${jobs.length} — ${identities}` : jobs.length], ["Output", outputs || "—"], ["Language", language], ["Speakers", speakers]]; } for (const [label, value] of entries) { const card = document.createElement("div"); card.className = "result-card"; const heading = document.createElement("strong"); heading.textContent = label; card.append(heading, String(value)); summary.append(card); } if (kind === "dry-run" && result.jobs?.length) { const table = document.createElement("table"); table.className = "queue-table plan-table"; table.innerHTML = "<thead><tr><th>Source files</th><th>Decision</th><th>Warnings</th></tr></thead>"; const body = document.createElement("tbody"); for (const job of result.jobs) { const episode = result.inspection?.episodes?.find(item => item.job_id === job.job_id); const files = episode?.sources?.map(source => source.fingerprint?.filename).filter(Boolean).join(", ") || "—"; const row = document.createElement("tr"); for (const value of [files, job.decision, job.warnings?.map(warning => warning.code).join(", ") || "None"]) { const cell = document.createElement("td"); cell.textContent = value; row.append(cell); } body.append(row); } table.append(body); summary.append(table); } }
async function queuePost(path, body) { const response = await fetch(path, {method: "POST", headers: {"Content-Type": "application/json", "Accept": "application/json", "X-EWP-CSRF": csrfToken}, body: JSON.stringify(body)}); const payload = await response.json(); if (!response.ok) throw new Error(`${payload.error.code}: ${payload.error.message}`); return payload; }
async function refreshJobs() { const payload = await loadJson("/api/v1/transcriptions"); const signature = JSON.stringify(payload.jobs); if (signature === jobsSignature) return; jobsSignature = signature; const container = document.querySelector("#transcription-jobs"); if (!payload.jobs.length) { container.innerHTML = "<p>No jobs in this server session.</p>"; return; } const table = document.createElement("table"); table.className = "queue-table"; const head = document.createElement("thead"); head.innerHTML = "<tr><th>Status</th><th>Job and settings</th><th>Input</th><th>Planned/actual result</th><th>Action</th></tr>"; const body = document.createElement("tbody"); for (const job of payload.jobs) { const row = document.createElement("tr"); const status = document.createElement("td"); status.className = `status-${job.status}`; status.textContent = job.status.toUpperCase(); const identity = document.createElement("td"); identity.textContent = `${job.planned_job_id} · ${job.language} · speakers: ${job.speaker_count}`; const input = document.createElement("td"); input.textContent = job.input_path; const output = document.createElement("td"); output.textContent = job.result_path || job.error?.message || shortName(job.planned_result_path); const action = document.createElement("td"); if (job.status === "staged") { const remove = document.createElement("button"); remove.type = "button"; remove.textContent = "Remove"; remove.addEventListener("click", async () => { try { await queuePost("/api/v1/transcriptions/remove", {job_id: job.job_id}); jobsSignature = ""; await refreshJobs(); } catch (error) { document.querySelector("#operation-status").textContent = error.message; } }); action.append(remove); } row.append(status, identity, input, output, action); body.append(row); } table.append(head, body); container.replaceChildren(table); }
document.querySelector("#workflow").addEventListener("submit", async event => { event.preventDefault(); const formElement = event.currentTarget; const submitter = event.submitter; const kind = submitter.value; const form = new FormData(formElement); const speakerValue = form.get("speaker_count"); const request = {path: form.get("path"), language: form.get("language"), speaker_count: speakerValue === "auto" ? "auto" : Number(speakerValue)}; if (form.get("output_directory")) request.output_directory = form.get("output_directory"); const status = document.querySelector("#operation-status"); const result = document.querySelector("#operation-result"); const summary = document.querySelector("#operation-summary"); submitter.disabled = true; status.textContent = kind === "inspect" ? "Inspecting…" : kind === "dry-run" ? "Planning…" : "Adding…"; result.textContent = ""; summary.replaceChildren(); try { const headers = {"Content-Type": "application/json", "Accept": "application/json"}; if (kind === "transcriptions") { request.confirmed = form.get("confirmed") === "on"; headers["X-EWP-CSRF"] = csrfToken; } const response = await fetch(`/api/v1/${kind}`, {method: "POST", headers, body: JSON.stringify(request)}); const payload = await response.json(); if (kind === "transcriptions") { if (response.ok) { status.textContent = "Added to staged queue"; formElement.elements.confirmed.checked = false; await refreshJobs(); } else { status.textContent = `${payload.error.code}: ${payload.error.message}`; result.textContent = JSON.stringify(payload.error, null, 2); } } else if (payload.status === "completed" && payload.result) { status.textContent = `${kind === "inspect" ? "Inspection" : "Dry-run"} completed`; showSummary(kind, payload.result, payload); result.textContent = JSON.stringify(payload.result, null, 2); } else { const error = payload.error || {code: "GUI_RESPONSE_INVALID", message: "The local service returned no result."}; status.textContent = `${error.code}: ${error.message}`; result.textContent = JSON.stringify(error, null, 2); } } catch (error) { status.textContent = `GUI_API_UNAVAILABLE: ${error.message}`; } finally { submitter.disabled = false; } });
document.querySelector("#start-queue").addEventListener("click", async event => { event.currentTarget.disabled = true; try { const payload = await queuePost("/api/v1/transcriptions/start", {}); document.querySelector("#operation-status").textContent = payload.queued ? `Started ${payload.queued} queued job(s)` : "No staged jobs to start"; await refreshJobs(); } catch (error) { document.querySelector("#operation-status").textContent = error.message; } finally { event.currentTarget.disabled = false; } });
document.querySelector("#workflow").addEventListener("reset", () => { document.querySelector("#operation-status").textContent = ""; document.querySelector("#operation-summary").replaceChildren(); document.querySelector("#operation-result").textContent = ""; document.querySelector("#raw-result").open = false; });
let correctionCandidate = null;
const correctionForm = document.querySelector("#correction-workflow");
function updateCorrectionProvider() { const cloud = correctionForm.elements.namedItem("provider").value === "openrouter"; document.querySelector("#openrouter-options").hidden = !cloud; correctionForm.elements.namedItem("allow_remote_endpoint").closest("label").hidden = cloud; correctionForm.elements.namedItem("model").value = cloud ? "google/gemini-2.5-flash" : ""; correctionForm.elements.namedItem("endpoint").value = cloud ? "https://openrouter.ai/api/v1" : "http://127.0.0.1:1234/v1"; }
correctionForm.elements.namedItem("provider").addEventListener("change", updateCorrectionProvider);
updateCorrectionProvider();
const correctionProviderSettings = document.createElement("details");
correctionProviderSettings.className = "provider-settings";
const correctionProviderSummary = document.createElement("summary");
correctionProviderSummary.textContent = "Provider settings";
correctionProviderSettings.append(correctionProviderSummary);
const correctionProviderNodes = [correctionForm.querySelector('label[for="correction-provider"]'), correctionForm.elements.namedItem("provider"), correctionForm.querySelector('label[for="correction-model"]'), correctionForm.elements.namedItem("model"), correctionForm.querySelector('label[for="correction-endpoint"]'), correctionForm.elements.namedItem("endpoint"), document.querySelector("#openrouter-options"), correctionForm.elements.namedItem("allow_remote_endpoint").closest("label")];
correctionForm.elements.namedItem("output_root").nextElementSibling.after(correctionProviderSettings);
correctionProviderSettings.append(...correctionProviderNodes);
const correctionModelInput = correctionForm.elements.namedItem("model");
const correctionModelInputLabel = correctionForm.querySelector('label[for="correction-model"]');
correctionModelInputLabel.textContent = "Manual model ID";
const correctionModelPresetLabel = document.createElement("label");
correctionModelPresetLabel.textContent = "Model";
const correctionModelPreset = document.createElement("select");
correctionModelPreset.innerHTML = '<option value="google/gemini-2.5-flash">Gemini 2.5 Flash (recommended) · input ≈3.33M tok/USD · output ≈400k tok/USD</option><option value="google/gemini-2.5-flash-lite">Gemini 2.5 Flash Lite · input ≈10M tok/USD · output ≈2.5M tok/USD</option><option value="google/gemini-2.5-pro">Gemini 2.5 Pro · input ≈800k tok/USD · output ≈100k tok/USD</option><option value="manual">Enter ID manually</option>';
correctionModelPresetLabel.append(correctionModelPreset);
correctionModelInputLabel.before(correctionModelPresetLabel);
const liveModelDetails = document.createElement("details");
liveModelDetails.className = "live-model-details";
liveModelDetails.innerHTML = '<summary>Check for current models and pricing</summary><p class="field-hint">This makes an external request to the selected provider to read current model availability and listed input/output prices. It does not send transcript text and never runs automatically.</p><button type="button" id="check-model-pricing">Check models and pricing</button><div id="model-pricing-result" role="status"></div>';
correctionModelInput.after(liveModelDetails);
function updateCorrectionModelChoice() { const cloud = correctionForm.elements.namedItem("provider").value === "openrouter"; correctionModelPresetLabel.hidden = !cloud; liveModelDetails.hidden = !cloud; if (!cloud) { correctionModelInputLabel.hidden = false; correctionModelInput.hidden = false; return; } const manual = correctionModelPreset.value === "manual"; correctionModelInputLabel.hidden = !manual; correctionModelInput.hidden = !manual; if (!manual) correctionModelInput.value = correctionModelPreset.value; setProviderCheckState("unknown", "Not checked"); }
correctionModelPreset.addEventListener("change", updateCorrectionModelChoice);
correctionForm.elements.namedItem("provider").addEventListener("change", updateCorrectionModelChoice);
const openRouterKeyButton = document.createElement("button");
openRouterKeyButton.type = "button";
openRouterKeyButton.textContent = "Set an OpenRouter API key";
const providerCheckButton = document.createElement("button");
providerCheckButton.type = "button";
providerCheckButton.textContent = "Check connection";
const providerCheckLight = document.createElement("span");
providerCheckLight.className = "connection-light connection-unknown";
providerCheckLight.setAttribute("aria-hidden", "true");
const providerCheckStatus = document.createElement("span");
providerCheckStatus.setAttribute("role", "status");
providerCheckStatus.textContent = "Not checked";
const providerActions = document.createElement("div");
providerActions.className = "actions";
providerActions.append(openRouterKeyButton, providerCheckButton);
const providerCheckResult = document.createElement("div");
providerCheckResult.className = "connection-status";
const providerCheckLabel = document.createElement("strong");
providerCheckLabel.textContent = "API check";
providerCheckResult.append(providerCheckLabel, providerCheckLight, providerCheckStatus);
const openRouterKeyStatus = document.createElement("p");
openRouterKeyStatus.className = "field-hint";
openRouterKeyStatus.classList.add("session-secret-status");
openRouterKeyStatus.setAttribute("role", "status");
document.querySelector("#openrouter-options .field-hint").textContent = "Use the server environment or set a session-only key below. Secrets are never written to project files or browser storage.";
document.querySelector("#openrouter-options").append(providerActions, providerCheckResult, openRouterKeyStatus);
const openRouterKeyDialog = document.createElement("dialog");
openRouterKeyDialog.innerHTML = '<form method="dialog"><h3>Set an OpenRouter API key</h3><p class="notice">Treat API keys as secrets. Use a dedicated key with a low spending limit; the project\'s 20-episode testing used substantially less than a USD $2 limit.</p><p>The key is sent only to this loopback server, kept only for the current server process, never written to project files or browser storage, and must be entered again after restarting the GUI.</p><label for="openrouter-api-key">API key</label><input id="openrouter-api-key" type="password" autocomplete="new-password" spellcheck="false"><div class="actions"><button type="button" class="primary" id="save-openrouter-key">Set key for this session</button><button type="button" id="cancel-openrouter-key">Cancel</button></div><p id="openrouter-key-dialog-status" role="status"></p></form>';
document.body.append(openRouterKeyDialog);
function updateOpenRouterKeyStatus() { openRouterKeyStatus.textContent = openRouterKeyConfigured ? "API key is used only in this server session; EWP Transcriber does not store API keys." : "No API key is configured for this server session."; }
openRouterKeyButton.addEventListener("click", () => { document.querySelector("#openrouter-api-key").value = ""; document.querySelector("#openrouter-key-dialog-status").textContent = ""; openRouterKeyDialog.showModal(); });
document.querySelector("#cancel-openrouter-key").addEventListener("click", () => openRouterKeyDialog.close());
document.querySelector("#save-openrouter-key").addEventListener("click", async () => { const input = document.querySelector("#openrouter-api-key"); const status = document.querySelector("#openrouter-key-dialog-status"); try { await queuePost("/api/v1/credentials/openrouter", {api_key: input.value}); input.value = ""; openRouterKeyConfigured = true; updateOpenRouterKeyStatus(); openRouterKeyDialog.close(); } catch (error) { input.value = ""; status.textContent = error.message; } });
function setProviderCheckState(state, message) { providerCheckLight.className = `connection-light connection-${state}`; providerCheckStatus.textContent = message; }
updateCorrectionModelChoice();
providerCheckButton.addEventListener("click", async () => { const form = new FormData(correctionForm); const reasoning = String(form.get("reasoning_max_tokens") || ""); providerCheckButton.disabled = true; setProviderCheckState("unknown", "Checking…"); try { const payload = await queuePost("/api/v1/corrections/check", {provider: form.get("provider"), model: form.get("model"), endpoint: form.get("endpoint"), allow_remote_endpoint: form.get("allow_remote_endpoint") === "on", reasoning_max_tokens: reasoning === "" ? null : Number(reasoning)}); setProviderCheckState("ok", `API OK · ${payload.model}`); } catch (error) { setProviderCheckState("error", error.message); } finally { providerCheckButton.disabled = false; } });
function compactTokens(value) { if (!value) return "unknown"; if (value >= 1000000) return `${(value / 1000000).toFixed(2).replace(/\.00$/, "")}M`; if (value >= 1000) return `${(value / 1000).toFixed(1).replace(/\.0$/, "")}k`; return String(value); }
document.querySelector("#check-model-pricing").addEventListener("click", async event => { const button = event.currentTarget; const result = document.querySelector("#model-pricing-result"); const modelIds = [...correctionModelPreset.options].map(option => option.value).filter(value => value !== "manual"); button.disabled = true; result.textContent = "Checking current external model data…"; try { const payload = await queuePost("/api/v1/corrections/models", {endpoint: correctionForm.elements.namedItem("endpoint").value, model_ids: modelIds}); const table = document.createElement("table"); table.className = "review-summary-table"; table.innerHTML = "<thead><tr><th>Model</th><th>Availability</th><th>Listed input</th><th>Listed output</th></tr></thead>"; const body = document.createElement("tbody"); for (const item of payload.items) { const row = document.createElement("tr"); const input = item.input ? `$${item.input.usd_per_million}/M · ≈${compactTokens(item.input.tokens_per_usd)} tok/USD` : "Unknown"; const output = item.output ? `$${item.output.usd_per_million}/M · ≈${compactTokens(item.output.tokens_per_usd)} tok/USD` : "Unknown"; for (const value of [item.id, item.available ? "Available" : "Unavailable", input, output]) { const cell = document.createElement("td"); cell.textContent = value; row.append(cell); } body.append(row); } table.append(body); result.replaceChildren(table); } catch (error) { result.textContent = error.message; } finally { button.disabled = false; } });
for (const name of ["provider", "model", "endpoint", "reasoning_max_tokens"]) correctionForm.elements.namedItem(name).addEventListener("change", () => setProviderCheckState("unknown", "Not checked"));
correctionForm.addEventListener("submit", async event => { event.preventDefault(); const submit = document.querySelector("#generate-correction"); const form = new FormData(correctionForm); const root = String(form.get("output_root") || "").replace(/[\\/]+$/, ""); const reasoning = String(form.get("reasoning_max_tokens") || ""); const request = {result_path: form.get("result_path"), output_directory: `${root}/correction-candidates`, resume_directory: `${root}/correction-state`, provider: form.get("provider"), model: form.get("model"), endpoint: form.get("endpoint"), allow_remote_endpoint: form.get("allow_remote_endpoint") === "on", allow_cloud: form.get("provider") === "openrouter", reasoning_max_tokens: reasoning === "" ? null : Number(reasoning), dictionary_path: form.get("dictionary_path"), project_id: form.get("project_id"), confirmed: form.get("confirmed") === "on"}; const status = document.querySelector("#correction-status"); const result = document.querySelector("#correction-result"); const summary = document.querySelector("#correction-summary"); correctionCandidate = null; document.querySelector("#review-correction").disabled = true; submit.disabled = true; status.textContent = "Correction is running; do not close the server."; result.textContent = ""; summary.replaceChildren(); try { const payload = await queuePost("/api/v1/corrections/generate", request); correctionCandidate = {...payload, output_root: root}; status.textContent = "Non-final correction candidate generated; manual review is required."; result.textContent = JSON.stringify(payload, null, 2); const table = document.createElement("table"); table.className = "review-summary-table"; const dictionary = payload.dictionary ? `${payload.dictionary.dictionary_id} · ${payload.dictionary.sha256}` : "None"; const rows = [["Final", "No — manual review required"], ["Candidate", shortName(payload.candidate_path)], ["Provider", payload.provider], ["Model", payload.model], ["Dictionary", dictionary], ["Changes", (payload.statistics?.substitutions || 0) + (payload.statistics?.insertions || 0) + (payload.statistics?.deletions || 0)], ["Warnings", payload.warnings?.length || 0]]; const body = document.createElement("tbody"); for (const [label, value] of rows) { const row = document.createElement("tr"); const heading = document.createElement("th"); heading.scope = "row"; heading.textContent = label; const cell = document.createElement("td"); cell.textContent = String(value); row.append(heading, cell); body.append(row); } table.append(body); summary.append(table); document.querySelector("#review-correction").disabled = false; } catch (error) { status.textContent = error.message; } finally { submit.disabled = false; } });
const translationForm = document.querySelector("#translation-workflow");
let translationCandidate = null;
let translationReview = null;
let appliedTranslation = "";
translationForm.addEventListener("submit", async event => { event.preventDefault(); const submit = document.querySelector("#generate-translation"); const form = new FormData(translationForm); const root = String(form.get("output_root") || "").replace(/[\\/]+$/, ""); const request = {result_path: form.get("result_path"), source_revision_path: form.get("source_revision_path"), output_directory: `${root}/translation-candidates`, resume_directory: `${root}/translation-state`, target_language: form.get("target_language"), model: form.get("model"), endpoint: form.get("endpoint"), allow_remote_endpoint: form.get("allow_remote_endpoint") === "on", output_mode: form.get("output_mode"), dictionary_path: form.get("dictionary_path"), confirmed: form.get("confirmed") === "on"}; const status = document.querySelector("#translation-status"); const result = document.querySelector("#translation-result"); const summary = document.querySelector("#translation-summary"); submit.disabled = true; status.textContent = "Translation is running; do not close the server."; result.textContent = ""; summary.replaceChildren(); try { const payload = await queuePost("/api/v1/translations/generate", request); status.textContent = payload.source_verification === "manually_verified" ? "Non-final translation candidate generated; semantic manual review is required." : `WARNING: source is ${payload.source_verification}, not manually verified. The non-final translation requires semantic manual review.`; result.textContent = JSON.stringify(payload, null, 2); const table = document.createElement("table"); table.className = "review-summary-table"; const dictionary = payload.dictionary ? `${payload.dictionary.dictionary_id} · ${payload.dictionary.sha256}` : "None"; const direction = `${payload.direction.source_language} → ${payload.direction.target_language}`; const rows = [["Final", "No — semantic review required"], ["Candidate", shortName(payload.candidate_path)], ["Direction", direction], ["Source", payload.source_verification], ["Provider", payload.provider], ["Model", payload.model], ["Dictionary", dictionary], ["Units", payload.statistics?.unit_count || 0], ["Warnings", payload.warnings?.length || 0]]; const body = document.createElement("tbody"); for (const [label, value] of rows) { const row = document.createElement("tr"); const heading = document.createElement("th"); heading.scope = "row"; heading.textContent = label; const cell = document.createElement("td"); cell.textContent = String(value); row.append(heading, cell); body.append(row); } table.append(body); summary.append(table); } catch (error) { status.textContent = error.message; } finally { submit.disabled = false; } });
let reviewDocument = null;
let reviewDirty = false;
let appliedRevisionPath = "";
let reviewSourceRevisionPath = "";
let reviewSectionIndex = 0;
const reviewForm = document.querySelector("#review-workflow");
const reviewStatus = document.querySelector("#review-status");
const reviewResult = document.querySelector("#review-result");
const reviewSummary = document.querySelector("#review-summary");
const reviewStorageKey = "ewp-active-review-v1";
const proceedToTranslation = document.createElement("button");
proceedToTranslation.type = "button";
proceedToTranslation.id = "proceed-to-translation";
proceedToTranslation.className = "primary";
proceedToTranslation.textContent = "Proceed to translation";
proceedToTranslation.disabled = true;
proceedToTranslation.title = "Apply a verified immutable revision before proceeding to translation.";
document.querySelector("#export-review").after(proceedToTranslation);
function joinedPath(root, child) { return `${root.replace(/[\\/]+$/, "")}/${child}`; }
function updateReviewDirectories() { const custom = document.querySelector("#custom-review-paths").checked; document.querySelector("#custom-review-directories").hidden = !custom; if (custom) return; const root = reviewForm.elements.namedItem("project_output_directory").value.trim(); reviewForm.elements.namedItem("review_output_directory").value = root ? joinedPath(root, "reviews") : ""; reviewForm.elements.namedItem("revision_output_directory").value = root ? joinedPath(root, "revisions") : ""; reviewForm.elements.namedItem("export_output_directory").value = root ? joinedPath(root, "exports") : ""; }
function reviewValue(name) { updateReviewDirectories(); return reviewForm.elements.namedItem(name).value; }
function persistReview() { if (!reviewDocument) return; localStorage.setItem(reviewStorageKey, JSON.stringify({result_path: reviewDocument.result_path, review_path: reviewDocument.review_path, project_output_directory: reviewValue("project_output_directory"), review_output_directory: reviewValue("review_output_directory"), revision_output_directory: reviewValue("revision_output_directory"), export_output_directory: reviewValue("export_output_directory"), custom_paths: document.querySelector("#custom-review-paths").checked, applied_revision_path: appliedRevisionPath})); }
async function rememberReviewSession() { if (!reviewDocument) return; await postReview("session/save", {project_output_directory: reviewValue("project_output_directory"), result_path: reviewDocument.result_path, review_path: reviewDocument.review_path, review_output_directory: reviewValue("review_output_directory"), revision_output_directory: reviewValue("revision_output_directory"), export_output_directory: reviewValue("export_output_directory"), applied_revision_path: appliedRevisionPath}); }
async function restoreReview() { const raw = localStorage.getItem(reviewStorageKey); if (!raw) return; try { const saved = JSON.parse(raw); reviewForm.elements.namedItem("result_path").value = saved.result_path || ""; reviewForm.elements.namedItem("project_output_directory").value = saved.project_output_directory || ""; document.querySelector("#custom-review-paths").checked = saved.custom_paths === true; for (const name of ["review_output_directory", "revision_output_directory", "export_output_directory"]) reviewForm.elements.namedItem(name).value = saved[name] || ""; updateReviewDirectories(); const payload = await postReview("load", {result_path: saved.result_path, review_path: saved.review_path}); renderReview(payload); appliedRevisionPath = saved.applied_revision_path || ""; if (appliedRevisionPath) { const exportButton = document.querySelector("#export-review"); exportButton.disabled = false; exportButton.title = "Export publication files from the applied verified revision."; setReviewStatus("Saved applied review restored", payload); showReviewSummary([["Publication", "Immutable revision already written"], ["Revision file", shortName(appliedRevisionPath)], ["Review file", shortName(payload.review_path)]]); } else { setReviewStatus("Saved review restored; preview is required again", payload); showReviewSummary([["Publication", "None — restored editable draft"], ["Review file", shortName(payload.review_path)], ["Source", payload.source_verification]]); } } catch (error) { localStorage.removeItem(reviewStorageKey); setReviewStatus(`GUI_REVIEW_RESTORE_FAILED: ${error.message}`); } }
async function postReview(action, body) { return queuePost(`/api/v1/reviews/${action}`, body); }
function setReviewStatus(message, payload = null) { reviewStatus.textContent = message; reviewSummary.replaceChildren(); reviewResult.textContent = payload ? JSON.stringify(payload, null, 2) : ""; document.querySelector("#review-raw").open = false; }
function showReviewSummary(entries) { const table = document.createElement("table"); table.className = "review-summary-table"; table.innerHTML = "<thead><tr><th>Review check</th><th>Result</th></tr></thead>"; const body = document.createElement("tbody"); for (const [label, value] of entries) { const row = document.createElement("tr"); const heading = document.createElement("th"); heading.scope = "row"; heading.textContent = label; const cell = document.createElement("td"); cell.textContent = String(value); row.append(heading, cell); body.append(row); } table.append(body); reviewSummary.replaceChildren(table); }
function markReviewDirty() { reviewDirty = true; appliedRevisionPath = ""; const apply = document.querySelector("#apply-review"); const exportButton = document.querySelector("#export-review"); apply.disabled = true; apply.title = "Save and preview the current draft before applying."; exportButton.disabled = true; exportButton.title = "Apply a verified immutable revision before exporting."; lockTranslationHandoff(); reviewForm.elements.namedItem("verified").checked = false; }
function lockTranslationHandoff() { proceedToTranslation.disabled = true; proceedToTranslation.title = "Apply a verified immutable revision before proceeding to translation."; }
function unlockTranslationHandoff() { proceedToTranslation.disabled = false; proceedToTranslation.title = "Fill translation source fields from this verified revision."; }
function lockReviewPublication() { const apply = document.querySelector("#apply-review"); const exportButton = document.querySelector("#export-review"); apply.disabled = true; apply.title = "Save and preview the current draft before applying."; exportButton.disabled = true; exportButton.title = "Apply a verified immutable revision before exporting."; lockTranslationHandoff(); }
new MutationObserver(() => { if (appliedRevisionPath && !document.querySelector("#export-review").disabled) unlockTranslationHandoff(); else lockTranslationHandoff(); }).observe(document.querySelector("#export-review"), {attributes: true, attributeFilter: ["disabled"]});
function updateReviewSections() { const sections = [...document.querySelectorAll(".review-anchor")]; const layout = document.querySelector("#review-layout").value; if (!sections.length) return; reviewSectionIndex = Math.max(0, Math.min(reviewSectionIndex, sections.length - 1)); sections.forEach((section, index) => { section.hidden = layout === "one" && index !== reviewSectionIndex; }); document.querySelector("#review-position").textContent = layout === "one" ? `Section ${reviewSectionIndex + 1} of ${sections.length}` : `${sections.length} sections`; document.querySelector("#previous-review-section").disabled = layout !== "one" || reviewSectionIndex === 0; document.querySelector("#next-review-section").disabled = layout !== "one" || reviewSectionIndex === sections.length - 1; }
function renderReview(document) { reviewDocument = document; reviewDirty = false; appliedRevisionPath = ""; reviewSectionIndex = 0; reviewForm.elements.namedItem("verified").checked = false; const identity = window.document.querySelector("#review-identity"); identity.textContent = `${document.job_id} · ${document.language} · source: ${document.source_verification}`; const editor = window.document.querySelector("#review-editor"); editor.replaceChildren(); document.anchors.forEach((anchor, anchorIndex) => { const group = window.document.createElement("fieldset"); group.className = "review-anchor"; const legend = window.document.createElement("legend"); legend.textContent = `Transcript section ${anchorIndex + 1}`; group.append(legend); anchor.blocks.forEach(block => { const row = window.document.createElement("div"); row.className = "review-block"; const speakerLabel = window.document.createElement("label"); speakerLabel.textContent = "Speaker"; const speaker = window.document.createElement("select"); for (const speakerId of document.speakers) { const option = window.document.createElement("option"); const label = document.speaker_labels?.[speakerId]; option.value = speakerId; option.textContent = label ? `${label} (${speakerId})` : speakerId; option.selected = speakerId === block.speaker_id; speaker.append(option); } speaker.addEventListener("change", () => { block.speaker_id = speaker.value; markReviewDirty(); }); speakerLabel.append(speaker); const textLabel = window.document.createElement("label"); textLabel.textContent = "Transcript text"; const text = window.document.createElement("textarea"); text.value = block.text; text.addEventListener("input", () => { block.text = text.value; markReviewDirty(); }); textLabel.append(text); row.append(speakerLabel, textLabel); group.append(row); }); editor.append(group); }); window.document.querySelector("#review-navigation").hidden = false; const layout = window.document.querySelector("#review-layout"); layout.value = localStorage.getItem("ewp-review-layout") || "one"; updateReviewSections(); window.document.querySelector("#save-review").disabled = false; window.document.querySelector("#preview-review").disabled = false; lockReviewPublication(); }
document.querySelector("#review-project-path").addEventListener("input", updateReviewDirectories);
document.querySelector("#custom-review-paths").addEventListener("change", updateReviewDirectories);
document.querySelector("#prepare-review").addEventListener("click", async () => { if (reviewDocument) { setReviewStatus("GUI_REVIEW_ACTIVE: Clear the current review before preparing another one."); return; } try { const payload = await postReview("prepare", {result_path: reviewValue("result_path"), review_output_directory: reviewValue("review_output_directory"), source_revision_path: reviewSourceRevisionPath}); reviewSourceRevisionPath = ""; renderReview(payload); persistReview(); await rememberReviewSession(); setReviewStatus("Editable review prepared", {review_path: payload.review_path, source: payload.source_verification}); showReviewSummary([["Publication", "None — editable draft only"], ["Review file", shortName(payload.review_path)], ["Source", payload.source_verification]]); } catch (error) { setReviewStatus(error.message); } });
document.querySelector("#review-correction").addEventListener("click", () => { if (!correctionCandidate) return; if (reviewDocument) { setReviewStatus("GUI_REVIEW_ACTIVE: Clear the current review before opening the correction candidate."); document.querySelector("#review-heading").scrollIntoView({behavior: "smooth", block: "start"}); return; } reviewForm.elements.namedItem("result_path").value = correctionCandidate.result_path; reviewForm.elements.namedItem("project_output_directory").value = correctionCandidate.output_root; document.querySelector("#custom-review-paths").checked = false; updateReviewDirectories(); reviewSourceRevisionPath = correctionCandidate.candidate_path; document.querySelector("#prepare-review").click(); document.querySelector("#review-heading").scrollIntoView({behavior: "smooth", block: "start"}); });
document.querySelector("#restore-review").addEventListener("click", async () => { if (reviewDocument) { setReviewStatus("GUI_REVIEW_ACTIVE: Clear the current review before restoring another one."); return; } try { const root = reviewValue("project_output_directory"); const payload = await postReview("session/restore", {project_output_directory: root}); const session = payload.session; reviewForm.elements.namedItem("result_path").value = session.result_path; const standard = ["review_output_directory", "revision_output_directory", "export_output_directory"].every(name => session[name] === joinedPath(root, name.replace("_output_directory", "s"))); document.querySelector("#custom-review-paths").checked = !standard; for (const name of ["review_output_directory", "revision_output_directory", "export_output_directory"]) reviewForm.elements.namedItem(name).value = session[name]; updateReviewDirectories(); renderReview(payload); appliedRevisionPath = session.applied_revision_path || ""; if (appliedRevisionPath) { const exportButton = document.querySelector("#export-review"); exportButton.disabled = false; exportButton.title = "Export publication files from the applied verified revision."; } persistReview(); setReviewStatus(appliedRevisionPath ? "Saved applied review restored from disk" : "Saved review restored from disk; preview is required again", payload); showReviewSummary([["Publication", appliedRevisionPath ? "Immutable revision already written" : "None — restored editable draft"], ["Review file", shortName(payload.review_path)], ["Session file", shortName(payload.session_path)]]); } catch (error) { setReviewStatus(error.message); } });
document.querySelector("#clear-review").addEventListener("click", () => { if (reviewDocument && !window.confirm("Clear the current review from this browser? Saved review files will remain on disk.")) return; reviewDocument = null; reviewDirty = false; appliedRevisionPath = ""; reviewSectionIndex = 0; localStorage.removeItem(reviewStorageKey); reviewForm.elements.namedItem("verified").checked = false; document.querySelector("#review-identity").textContent = ""; document.querySelector("#review-navigation").hidden = true; document.querySelector("#review-editor").replaceChildren(); document.querySelector("#save-review").disabled = true; document.querySelector("#preview-review").disabled = true; lockReviewPublication(); setReviewStatus("Current review cleared from the browser. Saved files were not deleted."); });
document.querySelector("#review-layout").addEventListener("change", event => { localStorage.setItem("ewp-review-layout", event.currentTarget.value); updateReviewSections(); });
document.querySelector("#previous-review-section").addEventListener("click", () => { reviewSectionIndex -= 1; updateReviewSections(); });
document.querySelector("#next-review-section").addEventListener("click", () => { reviewSectionIndex += 1; updateReviewSections(); });
document.querySelector("#save-review").addEventListener("click", async () => { if (!reviewDocument) return; try { const payload = await postReview("save", {result_path: reviewDocument.result_path, review_path: reviewDocument.review_path, review_sha256: reviewDocument.review_sha256, anchors: reviewDocument.anchors}); renderReview(payload); persistReview(); await rememberReviewSession(); setReviewStatus("Draft saved; preview is required again", {review_path: payload.review_path, review_sha256: payload.review_sha256}); } catch (error) { setReviewStatus(error.message); } });
document.querySelector("#preview-review").addEventListener("click", async () => { if (!reviewDocument) return; if (reviewDirty) { setReviewStatus("GUI_REVIEW_SAVE_REQUIRED: Save the current draft before preview."); return; } try { const payload = await postReview("preview", {result_path: reviewDocument.result_path, review_path: reviewDocument.review_path}); const statistics = payload.statistics || {}; const changes = ["substitutions", "merges", "splits", "insertions", "deletions", "punctuation_only_changes", "speaker_changes"].reduce((total, key) => total + (statistics[key] || 0), 0); const apply = document.querySelector("#apply-review"); apply.disabled = Boolean(appliedRevisionPath); apply.title = appliedRevisionPath ? "This saved review has already been applied." : "Publish this exact previewed draft as an immutable verified revision."; setReviewStatus(appliedRevisionPath ? "Preview passed; this review is already published" : "Preview passed; review remains unpublished", payload); showReviewSummary([["Publication", appliedRevisionPath ? "Immutable revision already written" : "None — validation only"], ["Planned revision", payload.revision_number], ["Source tokens", statistics.source_tokens], ["Revision tokens", statistics.revision_tokens], ["Changes", changes], ["Speaker changes", statistics.speaker_changes || 0], ["Alignment warnings", statistics.alignment_warnings || 0], ["Warnings", payload.warnings?.length || 0]]); } catch (error) { setReviewStatus(error.message); } });
document.querySelector("#apply-review").addEventListener("click", async () => { if (!reviewDocument) return; try { const payload = await postReview("apply", {result_path: reviewDocument.result_path, review_path: reviewDocument.review_path, revision_output_directory: reviewValue("revision_output_directory"), confirmed: reviewForm.elements.namedItem("verified").checked}); appliedRevisionPath = payload.revision_path; const apply = document.querySelector("#apply-review"); apply.disabled = true; apply.title = "This saved review has already been applied."; const exportButton = document.querySelector("#export-review"); exportButton.disabled = false; exportButton.title = "Export publication files from the applied verified revision."; unlockTranslationHandoff(); persistReview(); await rememberReviewSession(); setReviewStatus("Verified immutable revision applied", payload); showReviewSummary([["Publication", "Immutable revision written"], ["Revision", payload.revision_number], ["Revision file", shortName(payload.revision_path)], ["Warnings", payload.warnings?.length || 0]]); } catch (error) { setReviewStatus(error.message); } });
document.querySelector("#export-review").addEventListener("click", async () => { if (!reviewDocument || !appliedRevisionPath) return; const formats = [...reviewForm.querySelectorAll('input[name="format"]:checked')].map(item => item.value); try { const payload = await postReview("export", {result_path: reviewDocument.result_path, revision_path: appliedRevisionPath, export_output_directory: reviewValue("export_output_directory"), formats}); setReviewStatus("Verified exports completed", payload); showReviewSummary([["Revision", shortName(appliedRevisionPath)], ["Files written", payload.written?.length || 0], ["Files skipped", payload.skipped?.length || 0]]); } catch (error) { setReviewStatus(error.message); } });
proceedToTranslation.addEventListener("click", () => { if (!reviewDocument || !appliedRevisionPath) return; translationForm.elements.namedItem("result_path").value = reviewDocument.result_path; translationForm.elements.namedItem("source_revision_path").value = appliedRevisionPath; translationForm.elements.namedItem("output_root").value = reviewValue("project_output_directory"); translationForm.elements.namedItem("target_language").value = reviewDocument.language === "pl" ? "en" : "pl"; document.querySelector("#translation-status").textContent = "Verified transcript source loaded from the completed review step."; document.querySelector("#translation-heading").scrollIntoView({behavior: "smooth", block: "start"}); });
function parentPath(path) { const normalized = path.replace(/[\\/]+$/, ""); const separator = normalized.includes("\\") && !normalized.includes("/") ? "\\" : "/"; return normalized.split(/[\\/]/).slice(0, -1).join(separator) || separator; }
function addCompletedJobHandoffs() { document.querySelectorAll("#transcription-jobs tbody tr").forEach(row => { const cells = row.querySelectorAll("td"); if (cells.length < 5 || cells[0].textContent !== "COMPLETED" || cells[4].dataset.workflowActions === "true") return; const resultPath = cells[3].textContent; const outputRoot = parentPath(resultPath); const correction = document.createElement("button"); correction.type = "button"; correction.className = "primary"; correction.textContent = "Continue to correction"; correction.addEventListener("click", () => { correctionForm.elements.namedItem("result_path").value = resultPath; correctionForm.elements.namedItem("output_root").value = outputRoot; document.querySelector("#correction-status").textContent = "Completed canonical transcription loaded; configure optional correction before generating a candidate."; document.querySelector("#correction-heading").scrollIntoView({behavior: "smooth", block: "start"}); }); const review = document.createElement("button"); review.type = "button"; review.className = "primary"; review.textContent = "Continue to manual review"; review.addEventListener("click", () => { if (reviewDocument) { setReviewStatus("GUI_REVIEW_ACTIVE: Clear the current review before loading another transcription."); document.querySelector("#review-heading").scrollIntoView({behavior: "smooth", block: "start"}); return; } reviewSourceRevisionPath = ""; reviewForm.elements.namedItem("result_path").value = resultPath; reviewForm.elements.namedItem("project_output_directory").value = outputRoot; document.querySelector("#custom-review-paths").checked = false; updateReviewDirectories(); setReviewStatus("Completed canonical transcription loaded; prepare its editable manual review when ready."); document.querySelector("#review-heading").scrollIntoView({behavior: "smooth", block: "start"}); }); cells[4].dataset.workflowActions = "true"; cells[4].append(correction, review); }); }
new MutationObserver(addCompletedJobHandoffs).observe(document.querySelector("#transcription-jobs"), {childList: true, subtree: true});
window.addEventListener("beforeunload", event => { if (!reviewDirty) return; event.preventDefault(); event.returnValue = ""; });
const translationResultElement = document.querySelector("#translation-result");
new MutationObserver(() => { try { const payload = JSON.parse(translationResultElement.textContent); const form = new FormData(translationForm); translationCandidate = {...payload, revision_path: String(form.get("source_revision_path") || ""), output_root: String(form.get("output_root") || "").replace(/[\\/]+$/, "")}; document.querySelector("#review-translation").disabled = false; } catch (_) { /* incomplete operation output */ } }).observe(translationResultElement, {childList: true, characterData: true, subtree: true});
function translationReviewRequest(extra = {}) { return {review_path: translationReview?.review_path || "", result_path: translationCandidate.result_path, revision_path: translationCandidate.revision_path, parent_translation_path: translationCandidate.candidate_path, ...extra}; }
function resizeTranslationTarget(input) { input.style.height = "auto"; input.style.height = `${Math.max(input.scrollHeight, 48)}px`; }
function renderTranslationReview(documentValue) { translationReview = documentValue; const editor = document.querySelector("#translation-review-editor"); editor.replaceChildren(); documentValue.units.forEach((unit, index) => { const article = document.createElement("fieldset"); article.className = "translation-unit"; const legend = document.createElement("legend"); legend.textContent = `Translation unit ${index + 1}`; const sourceLabel = document.createElement("p"); sourceLabel.className = "translation-source-label"; sourceLabel.textContent = "Source"; const source = document.createElement("p"); source.className = "translation-source"; source.textContent = unit.source_text; const label = document.createElement("label"); label.textContent = "Target translation"; const input = document.createElement("textarea"); input.dataset.unitId = unit.unit_id; input.value = unit.target_text; input.addEventListener("input", () => resizeTranslationTarget(input)); label.append(input); article.append(legend, sourceLabel, source, label); editor.append(article); resizeTranslationTarget(input); }); document.querySelector("#save-translation-review").disabled = false; document.querySelector("#preview-translation-review").disabled = false; document.querySelector("#translation-review-status").textContent = `${documentValue.job_id} · ${documentValue.direction.source_language} → ${documentValue.direction.target_language} · source: ${documentValue.source_verification}`; document.querySelector("#translation-review-result").textContent = JSON.stringify(documentValue, null, 2); }
document.querySelector("#review-translation").addEventListener("click", async () => { const root = translationCandidate.output_root; try { const payload = await queuePost("/api/v1/translation-reviews/prepare", translationReviewRequest({review_output_directory: `${root}/translation-reviews`})); renderTranslationReview(payload); document.querySelector("#translation-review-heading").scrollIntoView({behavior: "smooth"}); } catch (error) { document.querySelector("#translation-review-status").textContent = error.message; } });
document.querySelector("#save-translation-review").addEventListener("click", async () => { const targets = [...document.querySelectorAll("#translation-review-editor textarea")].map(item => ({unit_id: item.dataset.unitId, target_text: item.value})); try { renderTranslationReview(await queuePost("/api/v1/translation-reviews/save", translationReviewRequest({review_sha256: translationReview.review_sha256, targets}))); document.querySelector("#apply-translation-review").disabled = true; } catch (error) { document.querySelector("#translation-review-status").textContent = error.message; } });
document.querySelector("#preview-translation-review").addEventListener("click", async () => { try { const payload = await queuePost("/api/v1/translation-reviews/preview", translationReviewRequest()); document.querySelector("#translation-review-result").textContent = JSON.stringify(payload, null, 2); const summary = document.querySelector("#translation-review-summary"); const table = document.createElement("table"); table.className = "review-summary-table"; const rows = [["Validation", "Passed"], ["Publication", "None — preview only"], ["Units", payload.statistics.unit_count], ["Source tokens", payload.statistics.source_tokens], ["Target tokens", payload.statistics.target_tokens], ["Warnings", payload.warnings.length]]; const body = document.createElement("tbody"); for (const [label, value] of rows) { const row = document.createElement("tr"); const heading = document.createElement("th"); heading.scope = "row"; heading.textContent = label; const cell = document.createElement("td"); cell.textContent = String(value); row.append(heading, cell); body.append(row); } table.append(body); summary.replaceChildren(table); document.querySelector("#translation-review-status").textContent = "Preview passed: exact source lineage, complete target text, and immutable unit ownership validated. No translation was published."; document.querySelector("#apply-translation-review").disabled = false; } catch (error) { document.querySelector("#translation-review-status").textContent = error.message; } });
document.querySelector("#apply-translation-review").addEventListener("click", async () => { try { const root = translationCandidate.output_root; const payload = await queuePost("/api/v1/translation-reviews/apply", translationReviewRequest({translation_output_directory: `${root}/accepted-translations`, confirmed: document.querySelector("#translation-review-confirmed").checked})); appliedTranslation = payload.translation_path; document.querySelector("#translation-review-result").textContent = JSON.stringify(payload, null, 2); document.querySelector("#translation-review-status").textContent = "Verified manual translation applied."; document.querySelector("#export-translation-review").disabled = false; } catch (error) { document.querySelector("#translation-review-status").textContent = error.message; } });
document.querySelector("#export-translation-review").addEventListener("click", async () => { try { const root = translationCandidate.output_root; const formats = [...document.querySelectorAll('input[name="translation-format"]:checked')].map(item => item.value); const payload = await queuePost("/api/v1/translation-reviews/audit-export", translationReviewRequest({translation_path: appliedTranslation, audit_output_directory: `${root}/translation-audits`, export_output_directory: `${root}/translation-exports`, formats})); document.querySelector("#translation-review-result").textContent = JSON.stringify(payload, null, 2); document.querySelector("#translation-review-status").textContent = "Verified translation audited and exported."; } catch (error) { document.querySelector("#translation-review-status").textContent = error.message; } });
const dictionaryForm = document.querySelector("#dictionary-workflow");
let dictionaryProposal = null;
function renderDictionaryProposal(payload) { dictionaryProposal = payload; const editor = document.querySelector("#dictionary-editor"); editor.replaceChildren(); payload.candidates.forEach((candidate, index) => { const fieldset = document.createElement("fieldset"); fieldset.className = "dictionary-candidate"; const legend = document.createElement("legend"); legend.textContent = `${index + 1}. ${candidate.source} → ${candidate.target}`; const meta = document.createElement("p"); meta.textContent = `${candidate.occurrences} occurrence(s) across ${candidate.case_count} case(s)`; const select = document.createElement("select"); select.dataset.source = candidate.source; select.dataset.target = candidate.target; for (const status of ["pending", "approved", "rejected"]) { const option = document.createElement("option"); option.value = status; option.textContent = status; option.selected = candidate.status === status; select.append(option); } fieldset.append(legend, meta, select); candidate.evidence.forEach(example => { const details = document.createElement("details"); const summary = document.createElement("summary"); summary.textContent = `Example · ${example.job_id}`; const source = document.createElement("p"); source.textContent = `Before: ${example.source_context}`; const target = document.createElement("p"); target.textContent = `After: ${example.target_context}`; details.append(summary, source, target); fieldset.append(details); }); editor.append(fieldset); }); document.querySelector("#save-dictionary-decisions").disabled = false; document.querySelector("#publish-dictionary").disabled = payload.counts.pending !== 0; document.querySelector("#dictionary-status").textContent = `${payload.project_id}: ${payload.candidates.length} candidates; ${payload.counts.pending} pending, ${payload.counts.approved} approved, ${payload.counts.rejected} rejected.`; document.querySelector("#dictionary-result").textContent = JSON.stringify(payload, null, 2); }
dictionaryForm.addEventListener("submit", async event => { event.preventDefault(); const form = new FormData(dictionaryForm); const request = {canonical_directory: form.get("canonical_directory"), revision_directory: form.get("revision_directory"), output_root: form.get("output_root"), project_id: form.get("project_id"), minimum_occurrences: Number(form.get("minimum_occurrences")), previous_dictionary: form.get("previous_dictionary")}; try { renderDictionaryProposal(await queuePost("/api/v1/dictionaries/propose", request)); } catch (error) { document.querySelector("#dictionary-status").textContent = error.message; } });
document.querySelector("#save-dictionary-decisions").addEventListener("click", async () => { const decisions = [...document.querySelectorAll("#dictionary-editor select")].map(item => ({source: item.dataset.source, target: item.dataset.target, status: item.value})); try { renderDictionaryProposal(await queuePost("/api/v1/dictionaries/save", {proposal_path: dictionaryProposal.proposal_path, proposal_sha256: dictionaryProposal.proposal_sha256, decisions})); } catch (error) { document.querySelector("#dictionary-status").textContent = error.message; } });
document.querySelector("#publish-dictionary").addEventListener("click", async () => { const form = new FormData(dictionaryForm); try { const payload = await queuePost("/api/v1/dictionaries/publish", {proposal_path: dictionaryProposal.proposal_path, dictionary_id: document.querySelector("#dictionary-id").value, output_root: form.get("output_root"), confirmed: document.querySelector("#dictionary-publish-confirmed").checked}); document.querySelector("#dictionary-status").textContent = "Versioned project dictionary published."; document.querySelector("#dictionary-result").textContent = JSON.stringify(payload, null, 2); } catch (error) { document.querySelector("#dictionary-status").textContent = error.message; } });
const dictionaryEditor = document.querySelector("#dictionary-editor");
const dictionarySummary = document.querySelector("#dictionary-summary");
dictionaryForm.after(dictionarySummary);
const dictionaryViewControls = document.createElement("div");
dictionaryViewControls.className = "dictionary-view-controls";
dictionaryViewControls.innerHTML = '<label>Candidate filter<select id="dictionary-filter"><option value="all">Show all</option><option value="pending">Only pending</option><option value="rejected">Only rejected</option><option value="hide-approved">Hide approved</option></select></label><label>Occurrence display<select id="dictionary-occurrence-layout"><option value="list">List</option><option value="sequential">Previous / next</option></select></label>';
dictionaryEditor.before(dictionaryViewControls);
function refreshDictionaryCandidates() { if (!dictionaryProposal) return; const filter = document.querySelector("#dictionary-filter").value; const layout = document.querySelector("#dictionary-occurrence-layout").value; [...dictionaryEditor.querySelectorAll(".dictionary-candidate")].forEach((card, index) => { const candidate = dictionaryProposal.candidates[index]; card.hidden = filter === "pending" ? candidate.status !== "pending" : filter === "rejected" ? candidate.status !== "rejected" : filter === "hide-approved" ? candidate.status === "approved" : false; const evidence = [...card.querySelectorAll("details")]; let position = Number(card.dataset.evidencePosition || 0); position = Math.min(position, Math.max(0, evidence.length - 1)); card.dataset.evidencePosition = String(position); evidence.forEach((item, evidenceIndex) => { item.hidden = layout === "sequential" ? evidenceIndex !== position : evidenceIndex >= 5 && card.dataset.showAll !== "true"; item.open = !item.hidden; }); const navigation = card.querySelector(".dictionary-evidence-navigation"); if (navigation) { navigation.hidden = layout !== "sequential" || evidence.length < 2; navigation.querySelector("span").textContent = `${position + 1} / ${evidence.length}`; } const more = card.querySelector(".dictionary-show-more"); if (more) { more.hidden = layout !== "list" || evidence.length <= 5; more.textContent = card.dataset.showAll === "true" ? "Show fewer occurrences" : `Show ${evidence.length - 5} more occurrences`; } }); }
function enhanceDictionaryProposal() { if (!dictionaryProposal) return; const table = document.createElement("table"); table.className = "review-summary-table"; const rows = [["Candidates", dictionaryProposal.candidates.length], ["Approved", dictionaryProposal.counts.approved], ["Rejected", dictionaryProposal.counts.rejected], ["Pending", dictionaryProposal.counts.pending]]; const body = document.createElement("tbody"); for (const [label, value] of rows) { const row = document.createElement("tr"); const heading = document.createElement("th"); heading.scope = "row"; heading.textContent = label; const cell = document.createElement("td"); cell.textContent = String(value); row.append(heading, cell); body.append(row); } table.append(body); dictionarySummary.replaceChildren(table); [...dictionaryEditor.querySelectorAll(".dictionary-candidate")].forEach(card => { const evidence = card.querySelectorAll("details"); if (evidence.length > 5) { const more = document.createElement("button"); more.type = "button"; more.className = "dictionary-show-more"; more.addEventListener("click", () => { card.dataset.showAll = card.dataset.showAll === "true" ? "false" : "true"; refreshDictionaryCandidates(); }); card.append(more); } if (evidence.length > 1) { const navigation = document.createElement("div"); navigation.className = "actions dictionary-evidence-navigation"; const previous = document.createElement("button"); previous.type = "button"; previous.textContent = "Previous occurrence"; const position = document.createElement("span"); const next = document.createElement("button"); next.type = "button"; next.textContent = "Next occurrence"; previous.addEventListener("click", () => { card.dataset.evidencePosition = String(Math.max(0, Number(card.dataset.evidencePosition || 0) - 1)); refreshDictionaryCandidates(); }); next.addEventListener("click", () => { card.dataset.evidencePosition = String(Math.min(evidence.length - 1, Number(card.dataset.evidencePosition || 0) + 1)); refreshDictionaryCandidates(); }); navigation.append(previous, position, next); card.append(navigation); } }); refreshDictionaryCandidates(); }
document.querySelector("#dictionary-filter").addEventListener("change", refreshDictionaryCandidates);
document.querySelector("#dictionary-occurrence-layout").addEventListener("change", refreshDictionaryCandidates);
new MutationObserver(() => { if (dictionaryProposal && dictionaryEditor.children.length) enhanceDictionaryProposal(); }).observe(dictionaryEditor, {childList: true});
const dictionaryStatus = document.querySelector("#dictionary-status");
new MutationObserver(() => { const message = dictionaryStatus.textContent; const confirmation = document.querySelector("#dictionary-publish-confirmed"); const dictionaryId = document.querySelector("#dictionary-id"); confirmation.closest("label").classList.toggle("field-error", message.includes("confirmation is required")); confirmation.setAttribute("aria-invalid", String(message.includes("confirmation is required"))); dictionaryId.classList.toggle("field-error", message.includes("Dictionary ID is required")); dictionaryId.setAttribute("aria-invalid", String(message.includes("Dictionary ID is required"))); if (message === "Versioned project dictionary published.") dictionaryStatus.scrollIntoView({behavior: "smooth", block: "center"}); }).observe(dictionaryStatus, {childList: true, characterData: true, subtree: true});
function installDictionaryPicker(pathInputId, kind) { const pathInput = document.querySelector(pathInputId); const container = document.createElement("div"); container.className = "dictionary-picker"; const catalogLabel = document.createElement("label"); catalogLabel.textContent = "Dictionary catalog directory"; const catalogInput = document.createElement("input"); catalogInput.value = "dictionaries"; const refresh = document.createElement("button"); refresh.type = "button"; refresh.textContent = "Refresh dictionary list"; const selectLabel = document.createElement("label"); selectLabel.textContent = `Available ${kind} dictionaries`; const select = document.createElement("select"); const empty = document.createElement("option"); empty.value = ""; empty.textContent = "None / use direct path below"; select.append(empty); catalogLabel.append(catalogInput); selectLabel.append(select); container.append(catalogLabel, refresh, selectLabel); pathInput.before(container); refresh.addEventListener("click", async () => { try { const payload = await queuePost("/api/v1/dictionaries/catalog", {catalog_directory: catalogInput.value}); select.replaceChildren(empty.cloneNode(true)); payload.items.filter(item => item.kind === kind).forEach(item => { const option = document.createElement("option"); option.value = item.path; const direction = kind === "translation" ? ` · ${item.source_language}→${item.target_language}` : ` · ${item.language}`; option.textContent = `${item.project_id} · ${item.dictionary_id} · v${item.version}${direction}`; select.append(option); }); } catch (error) { dictionaryStatus.textContent = error.message; } }); select.addEventListener("change", () => { if (select.value) pathInput.value = select.value; }); }
installDictionaryPicker("#correction-dictionary", "correction");
installDictionaryPicker("#translation-dictionary", "translation");
document.querySelectorAll(".dictionary-picker").forEach(picker => { const localStatus = document.createElement("p"); localStatus.className = "field-hint"; localStatus.setAttribute("role", "status"); localStatus.textContent = "Dictionary list not loaded."; picker.append(localStatus); const select = picker.querySelector("select"); new MutationObserver(() => { const count = Math.max(0, select.options.length - 1); localStatus.textContent = count ? `${count} compatible dictionary option(s) loaded.` : "No compatible dictionaries found in this catalog."; }).observe(select, {childList: true}); new MutationObserver(() => { if (dictionaryStatus.textContent.includes("GUI_DICTIONARY")) localStatus.textContent = dictionaryStatus.textContent; }).observe(dictionaryStatus, {childList: true, characterData: true, subtree: true}); });
function installConfirmationHighlight(statusSelector, confirmationSelector) { const status = document.querySelector(statusSelector); const confirmation = document.querySelector(confirmationSelector); const update = () => { const invalid = /GUI_[A-Z_]*CONFIRMATION_REQUIRED|confirmation is required/i.test(status.textContent); confirmation.closest("label").classList.toggle("field-error", invalid); confirmation.setAttribute("aria-invalid", String(invalid)); }; new MutationObserver(update).observe(status, {childList: true, characterData: true, subtree: true}); confirmation.addEventListener("change", () => { if (confirmation.checked) { confirmation.closest("label").classList.remove("field-error"); confirmation.setAttribute("aria-invalid", "false"); } }); }
installConfirmationHighlight("#review-status", '#review-workflow input[name="verified"]');
installConfirmationHighlight("#operation-status", '#workflow input[name="confirmed"]');
installConfirmationHighlight("#correction-status", '#correction-workflow input[name="confirmed"]');
installConfirmationHighlight("#translation-status", '#translation-workflow input[name="confirmed"]');
installConfirmationHighlight("#translation-review-status", "#translation-review-confirmed");
const workflowOutput = document.querySelector("#output-path");
const workflowActions = document.querySelector("#workflow .actions");
const workflowOptions = document.createElement("div");
workflowOptions.className = "workflow-options";
workflowOptions.innerHTML = '<label>Language<select name="language"><option value="pl" selected>Polish</option><option value="en">English</option><option value="auto">Auto-detect</option></select></label><label>Number of speakers<select name="speaker_count"><option value="auto" selected>Auto-detect</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option></select></label>';
workflowActions.before(workflowOptions);
document.querySelector("#workflow").addEventListener("submit", event => { const kind = event.submitter?.value; if (kind !== "dry-run" && kind !== "transcriptions") return; if (workflowOutput.value.trim()) return; event.preventDefault(); event.stopImmediatePropagation(); workflowOutput.classList.add("field-error"); workflowOutput.setAttribute("aria-invalid", "true"); document.querySelector("#operation-status").textContent = "GUI_OUTPUT_REQUIRED: Enter a shared output directory before dry-run or queue staging."; }, {capture: true});
workflowOutput.addEventListener("input", () => { if (!workflowOutput.value.trim()) return; workflowOutput.classList.remove("field-error"); workflowOutput.setAttribute("aria-invalid", "false"); });
start();
