"use strict";
const expectedApi = "1.0";
let csrfToken = "";
let jobsSignature = "";
async function loadJson(path) { const response = await fetch(path, {headers: {"Accept": "application/json"}}); if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json(); }
async function start() { const status = document.querySelector("#compatibility"); try { const [health, about, roots, session] = await Promise.all([loadJson("/api/v1/health"), loadJson("/api/v1/about"), loadJson("/api/v1/roots"), loadJson("/api/v1/session")]); if (health.api_version !== expectedApi) throw new Error("GUI_API_VERSION_MISMATCH"); csrfToken = session.csrf_token; status.textContent = "Local service ready"; document.querySelector("#application-version").textContent = `${about.application} v${about.application_version}`; document.querySelector("#api-version").textContent = `v${about.api_version}`; for (const [id, key] of [["license", "license_url"], ["source", "repository_url"], ["issues", "issues_url"]]) document.querySelector(`#${id}`).href = about[key]; const list = document.querySelector("#roots"); list.replaceChildren(...roots.roots.map(root => { const item = document.createElement("li"); item.textContent = root; return item; })); await refreshJobs(); setInterval(refreshJobs, 2000); } catch (error) { status.textContent = `GUI_API_UNAVAILABLE: ${error.message}`; } }
function shortName(path) { return path ? path.split(/[\\/]/).pop() : "—"; }
function showSummary(kind, result) { const summary = document.querySelector("#operation-summary"); summary.replaceChildren(); let entries; if (kind === "inspect") { entries = [["Episodes", result.episodes?.length ?? 0], ["Files", result.discovery?.files?.length ?? 0], ["Skipped", result.discovery?.skipped?.length ?? 0]]; } else { const jobs = result.jobs || []; const identities = jobs.map(job => job.job_id).join(", "); const outputs = jobs.map(job => shortName(job.outputs?.results || job.existing_result?.path)).join(", "); const language = result.language ? `${result.language} (auto)` : "—"; entries = [["Jobs", identities ? `${jobs.length} — ${identities}` : jobs.length], ["Output", outputs || "—"], ["Language", language]]; } for (const [label, value] of entries) { const card = document.createElement("div"); card.className = "result-card"; const heading = document.createElement("strong"); heading.textContent = label; card.append(heading, String(value)); summary.append(card); } if (kind === "dry-run" && result.jobs?.length) { const table = document.createElement("table"); table.className = "queue-table plan-table"; table.innerHTML = "<thead><tr><th>Source files</th><th>Decision</th><th>Warnings</th></tr></thead>"; const body = document.createElement("tbody"); for (const job of result.jobs) { const episode = result.inspection?.episodes?.find(item => item.job_id === job.job_id); const files = episode?.sources?.map(source => source.fingerprint?.filename).filter(Boolean).join(", ") || "—"; const row = document.createElement("tr"); for (const value of [files, job.decision, job.warnings?.map(warning => warning.code).join(", ") || "None"]) { const cell = document.createElement("td"); cell.textContent = value; row.append(cell); } body.append(row); } table.append(body); summary.append(table); } }
async function queuePost(path, body) { const response = await fetch(path, {method: "POST", headers: {"Content-Type": "application/json", "Accept": "application/json", "X-EWP-CSRF": csrfToken}, body: JSON.stringify(body)}); const payload = await response.json(); if (!response.ok) throw new Error(`${payload.error.code}: ${payload.error.message}`); return payload; }
async function refreshJobs() { const payload = await loadJson("/api/v1/transcriptions"); const signature = JSON.stringify(payload.jobs); if (signature === jobsSignature) return; jobsSignature = signature; const container = document.querySelector("#transcription-jobs"); if (!payload.jobs.length) { container.innerHTML = "<p>No jobs in this server session.</p>"; return; } const table = document.createElement("table"); table.className = "queue-table"; const head = document.createElement("thead"); head.innerHTML = "<tr><th>Status</th><th>Job</th><th>Input</th><th>Planned/actual result</th><th>Action</th></tr>"; const body = document.createElement("tbody"); for (const job of payload.jobs) { const row = document.createElement("tr"); const status = document.createElement("td"); status.className = `status-${job.status}`; status.textContent = job.status.toUpperCase(); const identity = document.createElement("td"); identity.textContent = job.planned_job_id; const input = document.createElement("td"); input.textContent = job.input_path; const output = document.createElement("td"); output.textContent = job.result_path || job.error?.message || shortName(job.planned_result_path); const action = document.createElement("td"); if (job.status === "staged") { const remove = document.createElement("button"); remove.type = "button"; remove.textContent = "Remove"; remove.addEventListener("click", async () => { try { await queuePost("/api/v1/transcriptions/remove", {job_id: job.job_id}); jobsSignature = ""; await refreshJobs(); } catch (error) { document.querySelector("#operation-status").textContent = error.message; } }); action.append(remove); } row.append(status, identity, input, output, action); body.append(row); } table.append(head, body); container.replaceChildren(table); }
document.querySelector("#workflow").addEventListener("submit", async event => { event.preventDefault(); const formElement = event.currentTarget; const submitter = event.submitter; const kind = submitter.value; const form = new FormData(formElement); const request = {path: form.get("path")}; if (form.get("output_directory")) request.output_directory = form.get("output_directory"); const status = document.querySelector("#operation-status"); const result = document.querySelector("#operation-result"); const summary = document.querySelector("#operation-summary"); submitter.disabled = true; status.textContent = kind === "inspect" ? "Inspecting…" : kind === "dry-run" ? "Planning…" : "Adding…"; result.textContent = ""; summary.replaceChildren(); try { const headers = {"Content-Type": "application/json", "Accept": "application/json"}; if (kind === "transcriptions") { request.confirmed = form.get("confirmed") === "on"; headers["X-EWP-CSRF"] = csrfToken; } const response = await fetch(`/api/v1/${kind}`, {method: "POST", headers, body: JSON.stringify(request)}); const payload = await response.json(); if (kind === "transcriptions") { if (response.ok) { status.textContent = "Added to staged queue"; formElement.elements.confirmed.checked = false; await refreshJobs(); } else { status.textContent = `${payload.error.code}: ${payload.error.message}`; result.textContent = JSON.stringify(payload.error, null, 2); } } else if (payload.status === "completed" && payload.result) { status.textContent = `${kind === "inspect" ? "Inspection" : "Dry-run"} completed`; showSummary(kind, payload.result); result.textContent = JSON.stringify(payload.result, null, 2); } else { const error = payload.error || {code: "GUI_RESPONSE_INVALID", message: "The local service returned no result."}; status.textContent = `${error.code}: ${error.message}`; result.textContent = JSON.stringify(error, null, 2); } } catch (error) { status.textContent = `GUI_API_UNAVAILABLE: ${error.message}`; } finally { submitter.disabled = false; } });
document.querySelector("#start-queue").addEventListener("click", async event => { event.currentTarget.disabled = true; try { const payload = await queuePost("/api/v1/transcriptions/start", {}); document.querySelector("#operation-status").textContent = payload.queued ? `Started ${payload.queued} queued job(s)` : "No staged jobs to start"; await refreshJobs(); } catch (error) { document.querySelector("#operation-status").textContent = error.message; } finally { event.currentTarget.disabled = false; } });
document.querySelector("#workflow").addEventListener("reset", () => { document.querySelector("#operation-status").textContent = ""; document.querySelector("#operation-summary").replaceChildren(); document.querySelector("#operation-result").textContent = ""; document.querySelector("#raw-result").open = false; });
let reviewDocument = null;
let reviewDirty = false;
let appliedRevisionPath = "";
const reviewForm = document.querySelector("#review-workflow");
const reviewStatus = document.querySelector("#review-status");
const reviewResult = document.querySelector("#review-result");
function reviewValue(name) { return reviewForm.elements.namedItem(name).value; }
async function postReview(action, body) { return queuePost(`/api/v1/reviews/${action}`, body); }
function setReviewStatus(message, payload = null) { reviewStatus.textContent = message; reviewResult.textContent = payload ? JSON.stringify(payload, null, 2) : ""; }
function markReviewDirty() { reviewDirty = true; appliedRevisionPath = ""; document.querySelector("#apply-review").disabled = true; document.querySelector("#export-review").disabled = true; reviewForm.elements.namedItem("verified").checked = false; }
function renderReview(document) { reviewDocument = document; reviewDirty = false; appliedRevisionPath = ""; reviewForm.elements.namedItem("verified").checked = false; const identity = window.document.querySelector("#review-identity"); identity.textContent = `${document.job_id} · ${document.language} · source: ${document.source_verification}`; const editor = window.document.querySelector("#review-editor"); editor.replaceChildren(); document.anchors.forEach((anchor, anchorIndex) => { const group = window.document.createElement("fieldset"); group.className = "review-anchor"; const legend = window.document.createElement("legend"); legend.textContent = `Transcript section ${anchorIndex + 1}`; group.append(legend); anchor.blocks.forEach(block => { const row = window.document.createElement("div"); row.className = "review-block"; const speakerLabel = window.document.createElement("label"); speakerLabel.textContent = "Speaker"; const speaker = window.document.createElement("select"); for (const speakerId of document.speakers) { const option = window.document.createElement("option"); const label = document.speaker_labels?.[speakerId]; option.value = speakerId; option.textContent = label ? `${label} (${speakerId})` : speakerId; option.selected = speakerId === block.speaker_id; speaker.append(option); } speaker.addEventListener("change", () => { block.speaker_id = speaker.value; markReviewDirty(); }); speakerLabel.append(speaker); const textLabel = window.document.createElement("label"); textLabel.textContent = "Transcript text"; const text = window.document.createElement("textarea"); text.value = block.text; text.addEventListener("input", () => { block.text = text.value; markReviewDirty(); }); textLabel.append(text); row.append(speakerLabel, textLabel); group.append(row); }); editor.append(group); }); window.document.querySelector("#save-review").disabled = false; window.document.querySelector("#preview-review").disabled = false; window.document.querySelector("#apply-review").disabled = true; window.document.querySelector("#export-review").disabled = true; }
document.querySelector("#prepare-review").addEventListener("click", async () => { try { const payload = await postReview("prepare", {result_path: reviewValue("result_path"), review_output_directory: reviewValue("review_output_directory")}); renderReview(payload); setReviewStatus("Editable review prepared", {review_path: payload.review_path, source: payload.source_verification}); } catch (error) { setReviewStatus(error.message); } });
document.querySelector("#save-review").addEventListener("click", async () => { if (!reviewDocument) return; try { const payload = await postReview("save", {result_path: reviewDocument.result_path, review_path: reviewDocument.review_path, review_sha256: reviewDocument.review_sha256, anchors: reviewDocument.anchors}); renderReview(payload); setReviewStatus("Draft saved; preview is required again", {review_path: payload.review_path, review_sha256: payload.review_sha256}); } catch (error) { setReviewStatus(error.message); } });
document.querySelector("#preview-review").addEventListener("click", async () => { if (!reviewDocument) return; if (reviewDirty) { setReviewStatus("GUI_REVIEW_SAVE_REQUIRED: Save the current draft before preview."); return; } try { const payload = await postReview("preview", {result_path: reviewDocument.result_path, review_path: reviewDocument.review_path}); document.querySelector("#apply-review").disabled = false; setReviewStatus("Preview passed; review remains unpublished", payload); } catch (error) { setReviewStatus(error.message); } });
document.querySelector("#apply-review").addEventListener("click", async () => { if (!reviewDocument) return; try { const payload = await postReview("apply", {result_path: reviewDocument.result_path, review_path: reviewDocument.review_path, revision_output_directory: reviewValue("revision_output_directory"), confirmed: reviewForm.elements.namedItem("verified").checked}); appliedRevisionPath = payload.revision_path; document.querySelector("#export-review").disabled = false; setReviewStatus("Verified immutable revision applied", payload); } catch (error) { setReviewStatus(error.message); } });
document.querySelector("#export-review").addEventListener("click", async () => { if (!reviewDocument || !appliedRevisionPath) return; const formats = [...reviewForm.querySelectorAll('input[name="format"]:checked')].map(item => item.value); try { const payload = await postReview("export", {result_path: reviewDocument.result_path, revision_path: appliedRevisionPath, export_output_directory: reviewValue("export_output_directory"), formats}); setReviewStatus("Verified exports completed", payload); } catch (error) { setReviewStatus(error.message); } });
start();
